---
name: build

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    env:
      CI: true
      HOMEBREW_NO_INSTALL_CLEANUP: true
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-latest
          - ubuntu-latest
          # TODO: uncomment macos next time we re-build both
          # - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # https://wiki.libsdl.org/SDL2/Installation#linuxunix
      # https://github.com/libsdl-org/SDL/blob/main/docs/README-linux.md
      - name: download dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev

      # https://wiki.libsdl.org/SDL2/Installation#macos
      - name: build and install
        if: matrix.os == 'macos-latest'
        run: |
          ./configure --prefix=$(pwd)/SDL2-2.28.5-macos && make -j 5 install
        working-directory: SDL
        env:
          CC: 'build-scripts/clang-fat.sh'

      # https://wiki.libsdl.org/SDL2/Installation#linuxunix
      - name: build and install
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./configure --prefix=$(pwd)/SDL2-2.28.5-linux && make -j 4 install
        working-directory: SDL

      - uses: actions/upload-artifact@v3
        with:
          name: SDL2-2.28.5
          path: |
            SDL/SDL2-2.28.5-macos
            SDL/SDL2-2.28.5-linux
          if-no-files-found: error
